### ISSUE TITLE
Vagrant provision required twice after install

### ISSUE THREAD

**Issue by tareiking** [Chassis/mailcatcher#1]
Installed as per docs and mailcatcher resolved, but no emails were received.

@BronsonQuick mentioned I should do another ```vagrant provision``` and send another email test. After second  ```vagrant provision``` mailcatcher worked as expected.

**Comment by BronsonQuick** [comment]
Alrighty. We're no longer maintaining this so I'm closing this off: https://github.com/Chassis/Chassis/pull/236#issuecomment-247811035
