### ISSUE TITLE
Old Ruby Version

### ISSUE THREAD

**Issue by dominicwhittle** [Chassis/mailcatcher#2]
I get the following error during provision:

```==> default: Error: Execution of '/opt/vagrant_ruby/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:  
==> default: 	i18n requires Ruby version >= 1.9.3.```

My chassis installation is new and seems to ship with ruby 1.8.7

I manually added the following to this extension's `chassis.pp` (based on https://github.com/Chassis/Chassis/issues/103) but it makes no difference. 
```package { "ruby":
    ensure => "latest"
}```

Does this extension usually "just work"? What am I missing?

**Comment by rmccue** [comment]
Hmm, sorry about that; I think we're installing the latest mailcatcher rather than pinning to a specific version, so they've likely updated and now require newer Ruby.

We could do one of two things here:
1) Update to a newer Ruby in this extension
2) Downgrade Mailcatcher to the last compatible version.

Will look into this.

**Comment by rmccue** [comment]
> My chassis installation is new and seems to ship with ruby 1.8.7

Hmm, the Gem page shows it should be compatible with Ruby 1.8.7+, so this could be an unintentional break upstream.

**Comment by dominicwhittle** [comment]
I got the impression from here that there's built in provisioning support for upgrading packages:  https://github.com/Chassis/Chassis/issues/103#issuecomment-64296975. But like I said, didn't work for me (but I don't really know what I'm doing...)

**Comment by dominicwhittle** [comment]
@rmccue oh right!

**Comment by rmccue** [comment]
There should be, yeah, but my guess is that the system thinks 1.8.7 *is* the latest version. :)

**Comment by rmccue** [comment]
Try this:

`package { "ruby1.9.1": ensure => latest }`

**Comment by dominicwhittle** [comment]
1.9.**3**, but otherwise perfect! 
`package { "ruby1.9.3": ensure => latest }`

**Comment by rmccue** [comment]
`ruby1.9.3` should be an alias to `ruby1.9.1` (as it's the internal API version) :)

**Comment by dominicwhittle** [comment]
Hmmm, it didn't work: 
```==> default: Error: Execution of '/opt/vagrant_ruby/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:
==> default: 	i18n requires Ruby version >= 1.9.3.
==> default: Error: /Stage[main]/Mailcatcher/Package[mailcatcher]/ensure: change from absent to present failed: Execution of '/opt/vagrant_ruby/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:
==> default: 	i18n requires Ruby version >= 1.9.3.
==> default: Notice: /Stage[main]/Main/Package[ruby1.9.1]/ensure: ensure changed 'purged' to 'latest'
==> default: Notice: /Stage[main]/Mailcatcher/Service[mailcatcher]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 47.98 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

**Comment by rmccue** [comment]
Hmm, looks like it might be using the wrong version of Ruby.

From `vagrant ssh`, can you check `ruby --version`?

**Comment by dominicwhittle** [comment]
```
$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

**Comment by rmccue** [comment]
Got it. Try `sudo update-alternatives --config ruby` and see if you can select 1.9.1/1.9.3 there.

We'll need to solve this in the extension itself as well; apologies for the painfulness here. [puppetlabs-ruby](https://github.com/puppetlabs/puppetlabs-ruby) might help.

**Comment by dominicwhittle** [comment]
That did it! 

```
vagrant@vagrant:~$ sudo update-alternatives --config ruby
There are 2 choices for the alternative ruby (providing /usr/bin/ruby).

  Selection    Path                Priority   Status
------------------------------------------------------------
* 0            /usr/bin/ruby1.8     50        auto mode
  1            /usr/bin/ruby1.8     50        manual mode
  2            /usr/bin/ruby1.9.1   10        manual mode

Press enter to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/bin/ruby1.9.1 to provide /usr/bin/ruby (ruby) in manual mode.
vagrant@vagrant:~$ ruby --version
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
```

**Comment by dominicwhittle** [comment]
And in case I wasn't clear: as at https://github.com/Chassis/mailcatcher/issues/2#issuecomment-81321537 mailcatcher is running successfully.

**Comment by rmccue** [comment]
Gotcha, thanks for reporting the issue, glad it's working now. :)

**Comment by dominicwhittle** [comment]
Thanks for super quick reply! I'm just sorry I'm not really able to contribute to the Chassis project, it's a sick piece of kit!

**Comment by BronsonQuick** [comment]
@dominicwhittle Thanks for picking this up! I've submitted: https://github.com/Chassis/mailcatcher/issues/2 to fix this :+1: props @rmccue for the assistance :smile:
