### ISSUE TITLE
Error on provision: unable to find `sennza:php`

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/mailcatcher#4]
This extension is still referring to the old class following the [name change upstream](https://github.com/Chassis/Chassis/pull/168/files).

**Comment by BronsonQuick** [comment]
@peterwilsoncc I fixed up the name change locally and tried to get this working again but alas I've decided https://github.com/Chassis/Chassis/issues/235 is a better option.

**Comment by BronsonQuick** [comment]
Alrighty. We're no longer maintaining this so I'm closing this off: https://github.com/Chassis/Chassis/pull/236#issuecomment-247811035
